<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Errors</title>
</head>

<body>
    <!-- JavaScript Errors - Throw and Try to Catch -->

    <!-- The try statement lets you test a block of code for errors.
        The catch statement lets you handle the error.
        The throw statement lets you create custom errors.
        The finally statement lets you execute code, after try and catch, regardless of the result. -->

    <!-- Errors Will Happen!
        When executing JavaScript code, different errors can occur.
        Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.-->

    <!-- Example
    In this example we misspelled "alert" as "adddlert" to deliberately produce an error -->
    <script>
        try {
            adddlert("Welcome Guest");
        } catch (error) {
            console.log(error.message);//adddlert is not defined
        }
    </script>
    <!-- JavaScript catches adddlert as an error, and executes the catch code to handle it. -->

    <!-- JavaScript try and catch
        The try statement allows you to define a block of code to be tested for errors while it is being executed.
        The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.
        The JavaScript statements try and catch come in pairs:

        try {
        Block of code to try
        } -->

    <!-- JavaScript Throws Errors
        When an error occurs, JavaScript will normally stop and generate an error message.
        The technical term for this is: JavaScript will throw an exception (throw an error).
        JavaScript will actually create an Error object with two properties: name and message. -->

    <!-- The throw Statement
        The throw statement allows you to create a custom error.
        Technically you can throw an exception (throw an error).
        The exception can be a JavaScript String, a Number, a Boolean or an Object: -->

    <!-- throw "Too big";    // throw a text
         throw 500;          // throw a number -->

    <!-- If you use throw together with try and catch, you can control program flow and generate custom error messages.-->

    <!-- Input Validation Example
        This example examines input. If the value is wrong, an exception (err) is thrown.

        The exception (err) is caught by the catch statement and a custom error message is displayed: -->
    <script>
        var message = "";
        var x = 11;
        try {
            if (x == "") throw "empty";
            if (isNaN(x)) throw "not a number";
            x = Number(x);
            if (x < 5) throw "too low";
            if (x > 10) throw "too high";

        } catch (error) {
            console.log(error);
        }
    </script>

    <!-- The finally Statement
        The finally statement lets you execute code, after try and catch, regardless of the result:

        Syntax
        try {
        Block of code to try
        }
        catch(err) {
        Block of code to handle errors
        }
        finally {
        Block of code to be executed regardless of the try / catch result
        } -->

    <script>
        var message = "";
        var x = 11;
        try {
            if (x == "") throw "empty";
            if (isNaN(x)) throw "not a number";
            x = Number(x);
            if (x < 5) throw "too low";
            if (x > 10) throw "too high";

        } catch (error) {
            console.log(error)
        } finally {
            console.log("*Finally Block code to be executed rather than thte results of try-catch*")
        }
    </script>

    <!-- The Error Object
        JavaScript has a built in error object that provides error information when an error occurs.
        The error object provides two useful properties: name and message.

        Error Object Properties
        Property	Description
        name	    Sets or returns an error name
        message	    Sets or returns an error message (a string)
        
        Error Name Values
        Six different values can be returned by the error name property:

        Error Name	    Description
        EvalError	    An error has occurred in the eval() function
        RangeError	    A number "out of range" has occurred
        ReferenceError	An illegal reference has occurred
        SyntaxError	    A syntax error has occurred
        TypeError	    A type error has occurred
        URIError	    An error in encodeURI() has occurred
        The six different values are described below. -->

    <!-- Eval Error
    An EvalError indicates an error in the eval() function.
    Newer versions of JavaScript do not throw EvalError. Use SyntaxError instead. -->

    <!-- Range Error
        A RangeError is thrown if you use a number that is outside the range of legal values.
        For example: You cannot set the number of significant digits of a number to 500. -->

    <script>
        var num = 1;
        try {
            num.toPrecision(500);//// A number cannot have 500 significant digits
        } catch (error) {
            console.log(error.name, error.message);

        }
    </script>

    <!-- Reference Error
    A ReferenceError is thrown if you use (reference) a variable that has not been declared -->
    <script>
        var x;
        try {
            x = y + 1;// y cannot be referenced (used)
        } catch (error) {
            console.log(error.name, error.message);
        }
    </script>

    <!-- Syntax Error
    A SyntaxError is thrown if you try to evaluate code with a syntax error. -->
    <script>
        try {
            eval("alert('Hello)"); // Missing ' will produce an error
        } catch (error) {
            console.log(error.name, error.message);
        }
    </script>

    <!-- Type Error
    A TypeError is thrown if you use a value that is outside the range of expected types -->
    <script>
        var num = 1;
        try {
            num.toUpperCase();// You cannot convert a number to upper case
        } catch (error) {
            console.log(error.name, error.message);

        }
    </script>

    <!-- URI (Uniform Resource Identifier) Error
    A URIError is thrown if you use illegal characters in a URI function -->
    <script>
        try {
            decodeURI("%%%");   // You cannot URI decode percent signs
        } catch (error) {
            console.log(error.name, error.message);
        }
    </script>

    <!-- Non-Standard Error Object Properties
        Mozilla and Microsoft defines some non-standard error object properties:

        fileName (Mozilla)
        lineNumber (Mozilla)
        columnNumber (Mozilla)
        stack (Mozilla)
        description (Microsoft)
        number (Microsoft)

        Do not use these properties in public web sites. They will not work in all browsers. -->

</body>

</html>