<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Javascript Promises</title>
</head>

<body>
    <!-- JavaScript Promises -->

    <!-- "I Promise a Result!"

        "Producing code" is code that can take some time
        "Consuming code" is code that must wait for the result
         A Promise is a JavaScript object that links producing code and consuming code -->


    <!-- JavaScript Promise Object
        A JavaScript Promise object contains both the producing code and calls to the consuming code -->

    <!-- Promise Syntax -->
    <script>
        let myPromise = new Promise(function (myResolve, myReject) {
            // "Producing Code" (May take some time)  

            myResolve();// when successful
            myReject();// when error
        });

        // "Consuming Code" (Must wait for a fulfilled Promise)
        myPromise.then(function (value) {
            /* code if successful */
        }, function (error) {
            /* code if some error */
        });
    </script>
    <!-- When the executing code obtains the result, it should call one of the two callbacks:

    Result	Call
    Success	myResolve(result value)
    Error	myReject(error object)
    Promise Object Properties

    A JavaScript Promise object can be:

    Pending
    Fulfilled
    Rejected

    The Promise object supports two properties: state and result.

    While a Promise object is "pending" (working), the result is undefined.
    When a Promise object is "fulfilled", the result is a value.
    When a Promise object is "rejected", the result is an error object.

    myPromise.state	myPromise.result
    "pending"	undefined
    "fulfilled"	a result value
    "rejected"	an error object
    You cannot access the Promise properties state and result.

    You must use a Promise method to handle promises.

    Promise How To
    Here is how to use a Promise:

    myPromise.then(
    function(value) { /* code if successful */ },
    function(error) { /* code if some error */ }
    );
    Promise.then() takes two arguments, a callback for success and another for failure.

    Both are optional, so you can add a callback for success or failure only. -->
    <script>
        function myDisplay(params) {
            document.write(params);
        }
        let myPromise1 = new Promise(function (myResolve, myReject) {
            let x = 0;

            //The producing code (this may take some time)
            if (x == 0) {
                myResolve("Ok");
            } else {
                myReject("Error");
            }
        });

        myPromise1.then(function (value) {
            myDisplay(value);
        }, function (error) {
            myDisplay(error);
        });
    </script>

    <!-- JavaScript Promise Examples
        To demonstrate the use of promises, we will use the callback examples from the previous chapter:

        Waiting for a Timeout
        Waiting for a File        -->

    <!-- Waiting for a Timeout
        
        Example Using Callback -->
    <p id="demo"></p>
    <script>
        setTimeout(() => document.getElementById("demo").innerHTML = "Hi", 3000);
    </script>

    <!-- Example Using Promise -->
    <p id="demo1"></p>
    <script>
        let myPromise2 = new Promise(function (myResolve, myReject) {

            //Producing Code
            setTimeout(function () {
                myResolve("Hello");
            }, 4000);
        });

        myPromise2.then(function (value) {
            document.getElementById("demo1").innerHTML = value;
        });
    </script>


    <!-- In Simple , Promise is an object that represents some pending tasks that can be fullfilled or can be rejected(failed) in near future. -->
    <!-- A promise has three states:

        pending: It is the initial state.
        Fulfilled: It indicates that the promised operation was successful.
        Rejected: It indicates that the promised operation was unsuccessful. -->

    <!-- Promise provides us two functions then() and catch() -->

    <!-- function inside then() is run as resolve() -->
    <!-- function inside catch() is run as reject() -->
    <script>
        function func1() {
            return new Promise(function (resolve, reject) {
                setTimeout(() => {
                    const error = true;
                    //const error = false;
                    if (!error) {
                        console.log("Function: Your Promise has been resolved");
                        resolve("Successfully");
                    }
                    else {
                        console.log("Function: Your Promise has not been resolved");
                        reject("Sorry not fulfilled");
                    }
                }, 2000);
            })
        }

        func1().then(function (value) {
            console.log("Pranay: Thanks for resolving " + value);
        }).catch(function (error) {
            console.log("Pranay: Very Bad bro " + error);
        })
    </script>
    <!-- Promise is used as callback substitute -->

    <!-- ECMAScript 2018 finalizes the full implementation of the Promise object with Promise.finally:

        Example
        let myPromise = new Promise();

        myPromise.then();
        myPromise.catch();
        myPromise.finally(); -->

    <!-- finally()
        Just like there’s a finally clause in a regular try {...} catch {...}, there’s finally in promises. -->

    <!-- The call .finally(f)in the sense that f always runs when the promise is settled: be it resolve or reject.
        finally is a good handler for performing cleanup, e.g. stopping our loading indicators, as they are not needed anymore,
        no matter what the outcome is. -->
    <script>
        function func1() {
            return new Promise(function (resolve, reject) {
                setTimeout(() => {
                    const result = true;
                    if (!result) {
                        console.log("Function is passing result");
                        resolve("Successfully");
                    } else {
                        console.log("Function is not passing result");
                        reject("Failing");
                    }
                }, 3000);
            })
        }

        func1().then(function (value) {
            console.log("Good you got the result " + value);
        }).catch(function (error) {
            console.log("Oops! Not getting the result its " + error);
        }).finally(function () {
            console.log("We Got the status");
        })
    </script>
</body>

</html>